name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platfrom: [win32] #[win32, x64]
    env:
      CONFIGURATION: Release
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create Directories
        run: |
          mkdir c:\src\downloads
          mkdir c:\src\lib
        shell: cmd
      - name: Download SDL
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: https://www.libsdl.org/release/SDL2-2.0.5.zip
          location: C:\src\downloads
      - name: Download FreeImage
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: http://downloads.sourceforge.net/freeimage/FreeImage3170.zip
          location: C:\src\downloads
      - name: Download FreeType
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: http://download.savannah.gnu.org/releases/freetype/freetype-2.7.tar.gz
          location: C:\src\downloads
      - name: Download curl
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: https://curl.haxx.se/download/curl-7.50.3.zip
          location: C:\src\downloads
      - name: Download rapidjson
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: https://github.com/Tencent/rapidjson/archive/v1.1.0.zip
          file-name: rapidjson-v1.1.0.zip 
          location: C:\src\downloads
      - name: Download VLC
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: https://github.com/RSATom/libvlc-sdk/archive/64ca3daa475a6539073f7544c740725b818642b2.zip
          file-name:  vlc-2.2.2.zip
          location: C:\src\downloads
      - name: Download VLC
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: http://download.videolan.org/pub/videolan/vlc/2.2.2/win32/vlc-2.2.2-win32.zip
          location: C:\src\downloads
      - name: Expand Downloads
        run: |
          cd c:\src\downloads
          echo "Expanding FreeImage..."
          7z x c:\src\downloads\FreeImage3170.zip -oc:\src\lib > NUL
          echo "Expanding FreeType..."
          7z x c:\src\downloads\freetype-2.7.tar.gz -oc:\src\downloads > NUL
          7z x c:\src\downloads\freetype-2.7.tar -oc:\src\lib > NUL
          echo "Expanding curl"
          7z x c:\src\downloads\curl-7.50.3.zip -oc:\src\lib > NUL
          echo "Expanding rapidjson"
          7z x c:\src\downloads\rapidjson-v1.1.0.zip -oc:\src\lib > NUL
          echo "Expanding VLC"
          7z x c:\src\downloads\vlc-2.2.2.zip -oc:\src\lib > NUL
        shell: cmd
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
      - name: Build FreeType
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com"  freetype.sln /upgrade
          msbuild freetype.sln /p:Configuration=Release /p:Platform="Win32"
        working-directory: c:\src\lib\freetype-2.7\builds\windows\vc2010
        shell: cmd
      - name: Patch FreeImage
        run: |
          (Get-Content C:\src\lib\FreeImage\Source\LibTIFF4\tif_config.h).replace('#define snprintf _snprintf', '') | Set-Content C:\src\lib\FreeImage\Source\LibTIFF4\tif_config.h
        shell: powershell
      - name: Build FreeImage
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com"  FreeImage.2013.sln /upgrade
          msbuild FreeImage.2013.sln /p:Configuration=Release /p:Platform="Win32"
        shell: cmd
        working-directory: c:\src\lib\FreeImage
      - name: Init Build SDL 2
        run: |
          mkdir build
        shell: cmd
        working-directory: c:\src\lib\SDL2-2.0.5
      - name: Build SDL 2
        run: |
          cmake -G "Visual Studio 14 2015" ..
          cd c:\src\lib\SDL2-2.0.5\build
          "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild" SDL2.sln /p:Configuration=Release /p:Platform="Win32"
        shell: cmd
        working-directory: c:\src\lib\SDL2-2.0.5\build
      - name: Build curl
        run: |
          '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86'
          nmake /f Makefile.vc mode=dll VC=14 DEBUG=yes
          nmake /f Makefile.vc mode=dll VC=14 DEBUG=no
        shell: cmd
        working-directory: c:\src\lib\curl-7.50.3\winbuild
      - name: Build EmulationStation
        run: |
          cd c:\src\EmulationStation
          git submodule update --init --recursive
          mkdir build
          cd build
          set ES_LIB_DIR=c:\src\lib
          cmake -g "Visual Studio 14 2015 x86" .. -DFREETYPE_INCLUDE_DIRS=%ES_LIB_DIR%\freetype-2.7\include -DFREETYPE_LIBRARY=%ES_LIB_DIR%\freetype-2.7\objs\vc2010\Win32\freetype27.lib -DFreeImage_INCLUDE_DIR=%ES_LIB_DIR%\FreeImage\Source -DFreeImage_LIBRARY=%ES_LIB_DIR%\FreeImage\Dist\x32\FreeImage.lib -DSDL2_INCLUDE_DIR=%ES_LIB_DIR%\SDL2-2.0.5\include -DSDL2_LIBRARY=%ES_LIB_DIR%\SDL2-2.0.5\build\Release\SDL2.lib;%ES_LIB_DIR%\SDL2-2.0.5\build\Release\SDL2main.lib;Imm32.lib;version.lib -DCURL_INCLUDE_DIR=%ES_LIB_DIR%\curl-7.50.3\include -DCURL_LIBRARY=%ES_LIB_DIR%\curl-7.50.3\builds\libcurl-vc14-x86-release-dll-ipv6-sspi-winssl\lib\libcurl.lib -DRAPIDJSON_INCLUDE_DIRS=%ES_LIB_DIR%\rapidjson-1.1.0\include -DVLC_INCLUDE_DIR=%ES_LIB_DIR%\libvlc-sdk-64ca3daa475a6539073f7544c740725b818642b2\include -DVLC_LIBRARIES=%ES_LIB_DIR%\libvlc-2.2.2\lib\msvc\libvlc.lib;%ES_LIB_DIR%\libvlc-2.2.2\lib\msvc\libvlccore.lib -DVLC_VERSION=1.0.0     
          cd c:\src\EmulationStation\build
          '"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild" emulationstation-all.sln /p:Configuration=Release /p:Platform="Win32"'
