name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platfrom: [win32, x64]
    env:
      CONFIGURATION: Release
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Create Directories
        run: |
          mkdir c:\src\downloads
          mkdir c:\src\lib
        shell: cmd
      - name: Download SDL
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: https://www.libsdl.org/release/SDL2-2.0.5.zip
          location: C:\src\downloads
      - name: Download FreeImage
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: http://downloads.sourceforge.net/freeimage/FreeImage3170.zip
          location: C:\src\downloads
      - name: Download FreeType
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: http://download.savannah.gnu.org/releases/freetype/freetype-2.7.tar.gz
          location: C:\src\downloads
      - name: Download curl
        uses: carlosperate/download-file-action@v1.0.0
        with:
          file-url: https://curl.haxx.se/download/curl-7.50.3.zip
          location: C:\src\downloads
